namespace TextToImageGonfyUiV2
{
    internal static class data
    {
        private static List<string> chosenStyles1 = new List<string>(4); // Списък с избрани стилове, с максимален размер 4



        static string[] styles1 = {
            "Photography | Aerial",
            "Photography | Architecture",
            "Photography | Black and White",
            "Photography | Cinematic",
            "Photography | Documentary",
            "Photography | Experimental",
            "Photography | Fashion",
            "Photography | Fashion Editorial",
            "Photography | Fine Art",
            "Photography | Flower",
            "Photography | Food",
            "Photography | Landscape",
            "Photography | Long exposure",
            "Photography | Low key",
            "Photography | Macro",
            "Photography | Microscopic",
            "Photography | Minimalist",
            "Photography | Mockup",
            "Photography | Night",
            "Photography | Pet",
            "Photography | Portrait",
            "Photography | Portrait > Cinematic",
            "Photography | Portrait > Closeup",
            "Photography | Portrait > Fantasy",
            "Photography | Product",
            "Photography | Reflection",
            "Photography | Sport",
            "Photography | Still Life",
            "Photography | Surreal",
            "Photography | Time-lapse",
            "Photography | Underwater",
            "Photography | Vintage",
            "Photography | Wildlife",
            "Painting | Abstract Expressionism",
            "Painting | Acrylic",
            "Painting | Aerosol",
            "Painting | Children Book Art",
            "Painting | Chinese Ink Brush",
            "Painting | Digital",
            "Painting | Digital Fantasy Game Art",
            "Painting | Fantasy Art",
            "Painting | Fantasy Cartoon",
            "Painting | Fantasy Digital Art",
            "Painting | Fantasy Game Concept Item",
            "Painting | Fresco",
            "Painting | Gouache",
            "Painting | Gouache Cartoon",
            "Painting | Graffiti",
            "Painting | Grimdark",
            "Painting | Impasto",
            "Painting | Impressionism Painting Style",
            "Painting | Magic Realism",
            "Painting | Oil Painting",
            "Painting | Palette Knife",
            "Painting | Pointillism",
            "Painting | Renaissance",
            "Painting | Retrofuturism",
            "Painting | Sumi-e Painting",
            "Painting | Watercolor",
            "Painting | Watercolor > Cartoon",
            "Painting | Watercolor on White Background",
            "Illustration | Art Deco",
            "Illustration | Anime",
            "Illustration | Anime > Chibi",
            "Illustration | Anime > Kawaii",
            "Illustration | Anime > Mecha",
            "Illustration | Anime > Realistic",
            "Illustration | Cartoon",
            "Illustration | Cartoon Character on White BG",
            "Illustration | Children's book",
            "Illustration | Fantasy",
            "Illustration | Fantasy Cartoon on White BG",
            "Illustration | Fashion",
            "Illustration | Game Art",
            "Illustration | Illuminated Manuscript",
            "Illustration | Pop Art",
            "Illustration | Retro",
            "Illustration | Modern",
            "Illustration | Modernism",
            "Illustration | Sticker",
            "Illustration | Sticker Cute",
            "Illustration | Sticker Watercolor",
            "Drawing | Blue Ballpoint Pen",
            "Drawing | Caricature",
            "Drawing | Caricature Extreme",
            "Drawing | Charcoal",
            "Drawing | Colored Pencil",
            "Drawing | Graphite",
            "Drawing | Ink",
            "Drawing | Pastel",
            "Drawing | Pen",
            "Drawing | Pencil",
            "Drawing | Scratchboard",
            "Drawing | Technical",
            "Drawing | Zentangle",
            "3D | Abstract",
            "3D | Abstract > Fluid Dynamics",
            "3D | Abstract > Soft Forms",
            "3D | Architectural",
            "3D | Character",
            "3D | Character > Cartoon",
            "3D | Character > Cartoon Cute",
            "3D | Game Asset",
            "3D | Hard Surface",
            "3D | Icon",
            "3D | Isometric",
            "3D | Low Poly",
            "3D | Mech",
            "3D | Model",
            "3D | Product",
            "3D | Sci-Fi",
            "3D | Vehicle",
            "Vector | Coloring Book Page",
            "Vector | Flat Art Style",
            "Vector | Line Art",
            "Vector | Logo Symbol",
            "Vector | Silhouette",
            "Vector | Silhouette Cute",
            "Design | Avatar",
            "Design | Banner",
            "Design | Brochure",
            "Design | Business card",
            "Design | Event Invitation",
            "Design | Favicon",
            "Design | Flyer",
            "Design | Icon Design",
            "Design | Icon Design Simple Black",
            "Design | Infographic",
            "Design | Letterhead",
            "Design | Logo",
            "Design | Magazine Layout",
            "Design | Menu",
            "Design | Packaging",
            "Design | Poster",
            "Design | Website",
            "Fashion | Beachwear",
            "Fashion | Bikini",
            "Fashion | Boho",
            "Fashion | Cosplay",
            "Fashion | Cyberpunk",
            "Fashion | Emo Fashion",
            "Fashion | Glamour",
            "Fashion | Goth",
            "Fashion | Metalhead",
            "Fashion | Normcore",
            "Fashion | Preppy",
            "Fashion | Psychobilly",
            "Fashion | Rave",
            "Fashion | Sci-Fi",
            "Fashion | Sexy",
            "Fashion | Sportswear",
            "Fashion | Steampunk",
            "Fashion | Streetwear",
            "Fashion | Vintage",
            "Fashion | Winter",
            "ART | African Traditional",
            "ART | Afrofuturism Art",
            "ART | Ancient Egyptian Mural",
            "ART | Atompunk",
            "ART | Baroque",
            "ART | Biomechanical",
            "ART | Biopunk",
            "ART | Byzantine Icon",
            "ART | Cartoon",
            "ART | Claymation",
            "ART | Comic Book Style",
            "ART | Constructivism",
            "ART | Cubism",
            "ART | Cybergoth Art",
            "ART | Cyberpunk",
            "ART | Dadaism",
            "ART | Dark Academia",
            "ART | Deco",
            "ART | Dieselpunk",
            "ART | Egyptian",
            "ART | Futurism",
            "ART | Gilded",
            "ART | Glitch",
            "ART | Gothic",
            "ART | Interstellar",
            "ART | Japanese Traditional",
            "ART | Linocut",
            "ART | Lucha Libre",
            "ART | Mayan",
            "ART | Minoan",
            "ART | Naive",
            "ART | Necropunk",
            "ART | Nouveau",
            "ART | Pixel Art",
            "ART | Pop Art",
            "ART | Propaganda",
            "ART | Psychedelic",
            "ART | Rococo",
            "ART | Solarpunk",
            "ART | Stencil",
            "ART | Street Art",
            "ART | Steampunk",
            "ART | Surrealism",
            "ART | Synthwave",
            "ART | Ukrainian Folk Art",
            "ART | Vaporwave",
            "ART | Westernpunk",
            "Craft | Ceramic",
            "Craft | Ceramic > Cibulak",
            "Craft | Ceramic > Glass",
            "Craft | Ceramic > Moche",
            "Craft | Ceramic > Porcelain",
            "Craft | Crochet",
            "Craft | Crochet > Amigurumi",
            "Craft | Cross-stitching",
            "Craft | Embossed",
            "Craft | Embroidery",
            "Craft | Felt",
            "Craft | Gobelin Tapestry",
            "Craft | Kirigami",
            "Craft | Knitting Art",
            "Craft | Lapidary",
            "Craft | Laser Engraving Wood",
            "Craft | Leatherworking",
            "Craft | Macrame",
            "Craft | Marquetry",
            "Craft | Metalwork",
            "Craft | Mosaic",
            "Craft | Mosaic > Roman",
            "Craft | Needlepoint",
            "Craft | Origami",
            "Craft | Paper Cut",
            "Craft | Plasticine",
            "Craft | Pyrography",
            "Craft | Quilted",
            "Craft | Scrapbooking",
            "Craft | Sculpture",
            "Craft | Sculpture > Bronze",
            "Craft | Sculpture > Alebrije",
            "Craft | Sculpture > Bas-relief",
            "Craft | Sculpture > Clay",
            "Craft | Sculpture > Haniwa",
            "Craft | Sculpture > Jade",
            "Craft | Sculpture > Marble",
            "Craft | Sculpture > Netsuke",
            "Craft | Sculpture > Olmec",
            "Craft | Sculpture > Gold",
            "Craft | Sculpture > Sand",
            "Craft | Sculpture > Stone",
            "Craft | Sculpture > Wood",
            "Craft | Sculpture > Wood Carving",
            "Craft | Shadowbox > Paper",
            "Craft | Shadowbox > Wood",
            "Craft | 3D Layered Plywood Wall Art",
            "Craft | Stained Glass",
            "Craft | Tapestry",
            "Experimental | Alien Creature 3D",
            "Experimental | Apocalyptic Surrealism",
            "Experimental | Aztec Sculpture 3D",
            "Experimental | Bio-Luminous Art",
            "Experimental | Bio-Mechanical Fantasy",
            "Experimental | Biomechanical Angel 3D",
            "Experimental | Cute Animal 3D",
            "Experimental | Cute Boy 3D",
            "Experimental | Cute Cyber Ninja 3D",
            "Experimental | Cute Cyberpunk",
            "Experimental | Cute Girl 3D",
            "Experimental | Cute Knight 3D",
            "Experimental | Cute Monster 3D",
            "Experimental | Cute Robot 3D",
            "Experimental | Cute Victorian",
            "Experimental | Cyber Couture",
            "Experimental | Cybernetic Flora",
            "Experimental | Dreamscape Mapping",
            "Experimental | Dreamwave",
            "Experimental | Dreamy Animal",
            "Experimental | Eldritch Minimalism",
            "Experimental | Ethereal Assassin 3D",
            "Experimental | Ethereal Fluidity",
            "Experimental | Ethereal Steam",
            "Experimental | Fae Fantasy",
            "Experimental | Fairy Tale Chronicles",
            "Experimental | Fairy Tale Cute",
            "Experimental | Geomancer 3D",
            "Experimental | Holographic Chic",
            "Experimental | Legends Digital Painting",
            "Experimental | Liquid Light",
            "Experimental | Mythical Mechanica 3D",
            "Experimental | Nebula Dreams",
            "Experimental | Neural Dreams",
            "Experimental | Occult Expressionism",
            "Experimental | Pastel Goth Cute",
            "Experimental | Phantasmagoric Abstract",
            "Experimental | Phantasmal Visions",
            "Experimental | Phantom Rococo",
            "Experimental | Quantum Sketching",
            "Experimental | Radiant Fantasy",
            "Experimental | Robot Cute",
            "Experimental | Shadow Mage 3D",
            "Experimental | Voodoo Surrealism",
            "Experimental | Whimsical Chibi",
        };

        public static bool AddStyle(string style, string senderStyle)
        {
            string styleToAdd = $"{senderStyle} | {style}"; // Форматираме стила предварително

            if (!chosenStyles1.Contains(styleToAdd) && chosenStyles1.Count < 4)
            {
                chosenStyles1.Add(styleToAdd);
                return true;
            }
            else
            {
                Console.WriteLine($"Style '{styleToAdd}' already exists or maximum of 4 styles reached.");
                return false; // Стилът вече съществува или е достигнат максималният брой стилове
            }
        }

        public static void RemoveStyle(string style, string senderStyle)
        {
            string styleToRemove = $"{senderStyle} | {style}";          
            chosenStyles1.Remove(styleToRemove);

        }

        public static List<string> GetSelectedStyleNames() => chosenStyles1;


        public static void ClearSelectedStyles() => chosenStyles1.Clear();

    }
}
